### ISSUE TITLE
ArityException. Wrong number of parameters specified in the documentation?

### ISSUE THREAD

**Issue by st23am** [awetzel/clojure-erlastic#2]
Using the calculator run-server example at the bottom of the Readme gives me a ArityException.

Is this because run-server now only takes 2 parameters? I apologize if my terminology is off. I am new to Clojure.

## form_filler.clj

```
(require '[pdfboxing.form :as form])
(require '[pdfboxing.merge :as pdf])
(require '[clojure.core.async :as async :refer  [<! >! <!! go]])
(require '[clojure-erlastic.core :refer  [run-server log]])
(use '[clojure.core.match :only  (match)])
(log "Starting ....")
(run-server
 (fn [] 0)
 (fn [term state] (match term
                         [:add n] [:noreply (+ state n)]
                         [:rem n] [:noreply (- state n)]
                         :get [:reply state state])) [])

(log "end application, clean if necessary")
```

## Exception

```
iex(2)> Starting ....
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (3) passed to: core/run-server, compiling:(/Users/st23am/src/elixir/mcc_gen/priv/pdf_filler/form_filler.clj:6:22)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$script_opt.invoke(main.clj:336)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (3) passed to: core/run-server
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:40)
	at user$eval7803.invoke(form_filler.clj:14)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 9 more
```

**Comment by awetzel** [comment]
Yes the README is not  right anymore, there are now only 2 parameters (or one with the default init function) because the initial state is the first message sent by the erlang port (before, the third parameter was the initial state).

So when you use `run-server` you have to keep that in mind when you code the erlang side, the first message is the initial state. That is meant to be used with `exos` on the elixir side, a very simple wrapper around `GenServer` taking that into account : https://github.com/awetzel/exos/blob/master/lib/exos.ex#L28-L29

**Comment by st23am** [comment]
Excellent thank you for getting back to me! Also Exos looks really cool. I'll check it out. :+1:
